package(
    default_visibility = ["//visibility:public"],
)

COPTS = [
    "-g",
    "-msse4", 
    "-msse4.2",
    "-D__STDC_FORMAT_MACROS",
    "-DBTHREAD_USE_FAST_PTHREAD_MUTEX",
    "-D__const__=",
    "-D_GNU_SOURCE",
    "-DUSE_SYMBOLIZE",
    "-DNO_TCMALLOC",
    "-D__STDC_LIMIT_MACROS", "-D__STDC_CONSTANT_MACROS",
    "-fPIC",
    "-Wno-unused-parameter",
    "-fpermissive",
    "-fno-omit-frame-pointer",
    "-DBRPC_WITH_GLOG=1",
    "-std=c++14",
    "-fopenmp",
	"-Iffmpeg",
	" -I/usr/include",
	
]

LINKOPTS = [
    "-fopenmp",
    "-lgcc_s",
    "-lstdc++",
    "-lpthread",
    "-ldl",
    "-lz",
    "-lgflags",
    "-lssl",
    "-lrt",
    "-lcrypto",
	"-lrlottie",
	"-lavcodec",
	" -lavformat",
	" -lavutil",
	" -lswscale",
	" -lpthread",
	" -lm",
	" -lswresample",
	" -lx264",
	"-lavcodec",
" -lavformat",
" -lavutil",
" -lavdevice",
" -lswresample",
" -lswscale",
" -lm",
#" -lva",
" -lpthread",
#" -lvorbis",
#" -lvpx",
#" -lopus",
" -lz",
#" -lpostproc",
" -ldl",
#" -lfdk-aac",
#" -lmp3lame",
#" -lvorbisenc",
#" -lvorbisfile",
#" -lx264",
#" -ltheora",
#" -ltheoraenc",
#" -ltheoradec",
" -ldl",
" -lrt",
#" -lx265",
#" -lbz2",
"-llzma",
]

cc_binary(
    name = "lottie2gifmp4",
    srcs = glob(["src/*.cpp", "src/*.h", "src/*.cc"]), 
    copts = COPTS,
    linkopts = LINKOPTS,
)
